import { Injectable } from '@nestjs/common';
import { ReportDto } from './dto/report.dto';
import { ReportGenerator } from './report-generator.service';

@Injectable()
export class ReportService {
  constructor(private readonly reportGenerator: ReportGenerator) {}

  async generateReport(): Promise<ReportDto | null> {
    const reportData = {
      cgUserSubSubProgrammeAllocationsReportData: [
        {
          __typename: 'CgSubSubProgrammeAllocationDto',
          Sub_SubProgram_Allocation_ID: 13,
          Year_ID: {
            __typename: 'CgFiscalYearsDto',
            Year_ID: 3,
            Fiscal_Year: '2021-2022',
            Start_Date: '2021-06-30T21:00:00.000Z',
            End_Date: '2022-06-29T21:00:00.000Z',
          },
          Sub_SubProgramme_ID: {
            __typename: 'CgSubSubProgrammeDto',
            Sub_SubProgramme_ID: 15,
            Sub_SubProgramme_Code: 'kids Next Door',
            Sub_SubProgramme_Name: 'TeenTitans',
          },
          Y0_Wage: 0,
          Y0_NonWage: 0,
          Y0_GoUDevt: 0,
          Y0_AIA: 0,
          Y0_Donor: 0,
          Y1_Wage: 31,
          Y1_NonWage: 32200,
          Y1_GoUDevt: 2000,
          Y1_AIA: 0,
          Y1_Donor: 8888888888,
          Y2_Wage: 2555555555.2999997,
          Y2_NonWage: 0,
          Y2_GoUDevt: 0,
          Y2_AIA: 9,
          Y2_Donor: 0,
          Y3_Wage: 0,
          Y3_NonWage: 0,
          Y3_GoUDevt: 0,
          Y3_AIA: 0,
          Y3_Donor: 0,
          Y4_Wage: 0,
          Y4_NonWage: 0,
          Y4_GoUDevt: 0,
          Y4_AIA: 0,
          Y4_Donor: 0,
          Y5_Wage: 0,
          Y5_NonWage: 0,
          Y5_GoUDevt: 0,
          Y5_AIA: 0,
          Y5_Donor: 0,
        },
        {
          __typename: 'CgSubSubProgrammeAllocationDto',
          Sub_SubProgram_Allocation_ID: 5,
          Year_ID: {
            __typename: 'CgFiscalYearsDto',
            Year_ID: 3,
            Fiscal_Year: '2021-2022',
            Start_Date: '2021-06-30T21:00:00.000Z',
            End_Date: '2022-06-29T21:00:00.000Z',
          },
          Sub_SubProgramme_ID: {
            __typename: 'CgSubSubProgrammeDto',
            Sub_SubProgramme_ID: 37,
            Sub_SubProgramme_Code: '123',
            Sub_SubProgramme_Name: 'Budget Programme',
          },
          Y0_Wage: 0,
          Y0_NonWage: 0,
          Y0_GoUDevt: 0,
          Y0_AIA: 0,
          Y0_Donor: 0,
          Y1_Wage: 32969,
          Y1_NonWage: 800,
          Y1_GoUDevt: 3100,
          Y1_AIA: 5,
          Y1_Donor: 0,
          Y2_Wage: 0,
          Y2_NonWage: 0,
          Y2_GoUDevt: 0,
          Y2_AIA: 0,
          Y2_Donor: 0,
          Y3_Wage: 0,
          Y3_NonWage: 0,
          Y3_GoUDevt: 0,
          Y3_AIA: 1,
          Y3_Donor: 0,
          Y4_Wage: 0,
          Y4_NonWage: 0,
          Y4_GoUDevt: 0,
          Y4_AIA: 0,
          Y4_Donor: 0,
          Y5_Wage: 0,
          Y5_NonWage: 0,
          Y5_GoUDevt: 0,
          Y5_AIA: 12,
          Y5_Donor: 0,
        },
        {
          __typename: 'CgSubSubProgrammeAllocationDto',
          Sub_SubProgram_Allocation_ID: 19,
          Year_ID: {
            __typename: 'CgFiscalYearsDto',
            Year_ID: 3,
            Fiscal_Year: '2021-2022',
            Start_Date: '2021-06-30T21:00:00.000Z',
            End_Date: '2022-06-29T21:00:00.000Z',
          },
          Sub_SubProgramme_ID: {
            __typename: 'CgSubSubProgrammeDto',
            Sub_SubProgramme_ID: 59,
            Sub_SubProgramme_Code: '111',
            Sub_SubProgramme_Name: 'test-sub-sub',
          },
          Y0_Wage: 0,
          Y0_NonWage: 0,
          Y0_GoUDevt: 0,
          Y0_AIA: 0,
          Y0_Donor: 0,
          Y1_Wage: 797000,
          Y1_NonWage: 65022,
          Y1_GoUDevt: 3822.545,
          Y1_AIA: 0,
          Y1_Donor: 0.5,
          Y2_Wage: 0,
          Y2_NonWage: 0,
          Y2_GoUDevt: 0,
          Y2_AIA: 0,
          Y2_Donor: 0,
          Y3_Wage: 0,
          Y3_NonWage: 0,
          Y3_GoUDevt: 0,
          Y3_AIA: 0,
          Y3_Donor: 0,
          Y4_Wage: 0,
          Y4_NonWage: 0,
          Y4_GoUDevt: 0,
          Y4_AIA: 7,
          Y4_Donor: 0,
          Y5_Wage: 0,
          Y5_NonWage: 0,
          Y5_GoUDevt: 0,
          Y5_AIA: 0,
          Y5_Donor: 0,
        },
      ],
    };

    const generatedReport = await this.reportGenerator.generate(
      'Sub Sub Programmes Allocations',
      'reports/Test.rdlx-json',
      reportData,
    );

    return {
      Report_Generated: generatedReport !== null ? true : false,
      Report_Path: generatedReport,
    };
  }
}
